spring:
  main:
    allow-circular-references: true
  application:
    name: frontend
logging:
  level:
    root: INFO
server:
  port: 51586
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8775/eureka}
      fetchRegistry: false
